# Generated by Django 6.0 on 2025-12-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="room_area",
            field=models.DecimalField(
                decimal_places=2,
                default=60,
                max_digits=10,
                verbose_name="Diện tích phòng",
            ),
            preserve_default=False,
        ),
    ]
