# Generated by Django 5.2.7 on 2025-12-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0002_room_room_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Đang trống"),
                    ("unavailable", "Không còn trống"),
                    ("maintenance", "Bảo trì"),
                ],
                default="available",
                max_length=12,
                verbose_name="Trạng thái",
            ),
        ),
    ]
