# Generated by Django 6.0 on 2025-12-25 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0003_alter_room_status'),
        ('resident', '0003_resident_relationship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['building', 'floor_number', 'room_number'], 'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AddField(
            model_name='building',
            name='total_availble_rooms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Số phòng còn trống'),
        ),
        migrations.AddField(
            model_name='building',
            name='total_rooms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tổng số phòng'),
        ),
        migrations.AddField(
            model_name='room',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_owner', to='resident.resident', verbose_name='Chủ sở hữu'),
        ),
        migrations.AddField(
            model_name='room',
            name='rent_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Giá thuê'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_residents',
            field=models.ManyToManyField(blank=True, related_name='room_residents', to='resident.resident', verbose_name='Thành viên'),
        ),
        migrations.AlterField(
            model_name='building',
            name='total_floors',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tổng số tầng'),
        ),
        migrations.AlterField(
            model_name='room',
            name='type_listing',
            field=models.CharField(choices=[('rent', 'Cho thuê'), ('sale', 'Bán')], max_length=10, verbose_name='Loại hình kinh doanh'),
        ),
    ]
