# Generated by Django 6.0 on 2025-12-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0004_alter_room_options_building_total_availble_rooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bathroom_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Số phòng tắm'),
        ),
        migrations.AddField(
            model_name='room',
            name='bedroom_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Số phòng ngủ'),
        ),
    ]
