# Generated by Django 6.0 on 2025-12-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0005_room_bathroom_count_room_bedroom_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='bathroom_count',
            field=models.PositiveIntegerField(verbose_name='Số phòng tắm'),
        ),
        migrations.AlterField(
            model_name='room',
            name='bedroom_count',
            field=models.PositiveIntegerField(verbose_name='Số phòng ngủ'),
        ),
    ]
