# Generated by Django 6.0 on 2026-01-04 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0006_alter_room_bathroom_count_alter_room_bedroom_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='total_availble_rooms',
        ),
        migrations.RemoveField(
            model_name='building',
            name='total_rooms',
        ),
    ]
