# Generated by Django 5.2.7 on 2025-12-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resident",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "citizen_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Số CMND/CCCD"
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Tên")),
                ("last_name", models.CharField(max_length=50, verbose_name="Họ")),
                ("date_of_birth", models.DateField(verbose_name="Ngày sinh")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Nam"), ("female", "Nữ"), ("other", "Khác")],
                        max_length=10,
                        verbose_name="Giới tính",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Số điện thoại"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, verbose_name="Email"
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Địa chỉ")),
            ],
            options={
                "verbose_name": "Cư dân",
                "verbose_name_plural": "Cư dân",
                "db_table": "resident",
                "ordering": ["-created_at"],
            },
        ),
    ]
