# Generated by Django 5.2.7 on 2025-12-23 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0001_initial"),
        ("resident", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="residents",
                to="building.building",
                verbose_name="Tòa nhà",
            ),
        ),
        migrations.AddField(
            model_name="resident",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="residents",
                to="building.room",
                verbose_name="Căn hộ",
            ),
        ),
    ]
