# Generated by Django 5.2.7 on 2025-12-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resident", "0002_resident_building_resident_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("owner", "Chủ hộ"),
                    ("spouse", "Vợ/Chồng"),
                    ("child", "Con"),
                    ("parent", "Bố/Mẹ"),
                    ("relative", "Người thân"),
                    ("tenant", "Khách thuê"),
                    ("other", "Khác"),
                ],
                default="tenant",
                max_length=20,
                verbose_name="Quan hệ với chủ hộ",
            ),
        ),
    ]
