# Generated by Django 6.0 on 2026-01-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0003_resident_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='status',
            field=models.CharField(choices=[('living', 'Đang sống'), ('moved_out', 'Đã chuyển đi')], default='living', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
