# Generated by Django 5.2.7 on 2025-12-22 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("building", "0001_initial"),
        ("resident", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã hợp đồng"
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("rent", "Hợp đồng thuê"),
                            ("sale", "Hợp đồng mua bán"),
                        ],
                        max_length=10,
                        verbose_name="Loại hợp đồng",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Ngày bắt đầu")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày kết thúc"
                    ),
                ),
                ("sign_date", models.DateField(verbose_name="Ngày ký")),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Tổng giá trị (VNĐ)",
                    ),
                ),
                (
                    "price_per_month",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Giá thuê/tháng (VNĐ)",
                    ),
                ),
                (
                    "deposit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Tiền cọc (VNĐ)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Đang chờ duyệt"),
                            ("active", "Đang hiệu lực"),
                            ("expired", "Đã hết hạn"),
                            ("terminated", "Đã chấm dứt"),
                            ("rejected", "Từ chối"),
                        ],
                        default="pending",
                        max_length=12,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="resident.resident",
                        verbose_name="Cư dân",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="building.room",
                        verbose_name="Căn hộ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hợp đồng",
                "verbose_name_plural": "Hợp đồng",
                "db_table": "contract",
                "ordering": ["-sign_date"],
            },
        ),
    ]
