# Generated by Django 6.0 on 2025-12-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Đang chờ duyệt"),
                    ("active", "Đang hiệu lực"),
                    ("expired", "Đã hết hạn"),
                    ("terminated", "Đã chấm dứt"),
                    ("rejected", "Từ chối"),
                    ("will_expire", "Sắp hết hạn"),
                ],
                default="pending",
                max_length=12,
                verbose_name="Trạng thái",
            ),
        ),
    ]
