# Generated by Django 5.2.7 on 2025-12-24 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("building", "0001_initial"),
        ("contract", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã hóa đơn"
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("electricity", "Hoá đơn điện"),
                            ("water", "Hoá đơn nước"),
                            ("internet", "Hoá đơn internet"),
                            ("rent", "Hoá đơn tiền thuê phòng"),
                            ("maintenance", "Hoá đơn bảo trì"),
                            ("other", "Hoá đơn khác"),
                        ],
                        max_length=20,
                        verbose_name="Dịch vụ",
                    ),
                ),
                (
                    "count_unit",
                    models.IntegerField(default=1, verbose_name="Số lượng đơn vị"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Đơn giá (VNĐ)"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Tổng tiền (VNĐ)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("paid", "Đã thanh toán"),
                            ("unpaid", "Chưa thanh toán"),
                            ("overdue", "Quá hạn"),
                        ],
                        max_length=10,
                        verbose_name="Trạng thái",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Ngày thu phí")),
                (
                    "date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày nộp phí"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày hết hạn"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="contract.contract",
                        verbose_name="Hợp đồng",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="building.room",
                        verbose_name="Phòng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hóa đơn",
                "verbose_name_plural": "Hóa đơn",
                "db_table": "invoice",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["service", "status"], name="invoice_service_7c83bf_idx"
                    )
                ],
            },
        ),
    ]
