# Generated by Django 5.2.7 on 2025-12-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_title",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Nội dung hóa đơn"
            ),
        ),
    ]
