# Generated by Django 5.2.7 on 2025-12-26 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0002_invoice_invoice_title"),
        ("resident", "0003_resident_relationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="resident",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="resident.resident",
                verbose_name="Chủ hộ",
            ),
        ),
    ]
