# Generated by Django 5.2.7 on 2025-12-22 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "building_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã tòa nhà"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Tên tòa nhà")),
                ("address", models.TextField(verbose_name="Địa chỉ")),
                (
                    "total_floors",
                    models.PositiveIntegerField(verbose_name="Tổng số tầng"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Đang hoạt động"),
                            ("inactive", "Ngừng hoạt động"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="Trạng thái",
                    ),
                ),
            ],
            options={
                "verbose_name": "Building",
                "verbose_name_plural": "Buildings",
                "db_table": "building",
                "ordering": ["building_id"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã căn hộ"
                    ),
                ),
                ("floor_number", models.PositiveIntegerField(verbose_name="Số tầng")),
                (
                    "room_number",
                    models.CharField(max_length=10, verbose_name="Số phòng"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Đang trống"),
                            ("unavailable", "Không còn trống"),
                        ],
                        default="available",
                        max_length=12,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "type_listing",
                    models.CharField(
                        choices=[("rent", "Cho thuê"), ("sale", "Bán")],
                        max_length=10,
                        verbose_name="Loại hình",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="building.building",
                        verbose_name="Tòa nhà",
                    ),
                ),
            ],
            options={
                "verbose_name": "Căn hộ",
                "verbose_name_plural": "Căn hộ",
                "db_table": "room",
                "ordering": ["building", "floor_number", "room_number"],
            },
        ),
    ]
