# Generated by Django 5.2.7 on 2025-12-23 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("building", "0001_initial"),
        ("contract", "0001_initial"),
        ("resident", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Tiêu đề")),
                ("message", models.TextField(verbose_name="Nội dung")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("contract_expiring", "Hợp đồng sắp hết hạn"),
                            ("contract_expired", "Hợp đồng đã hết hạn"),
                            ("payment_reminder", "Nhắc nhở thanh toán dịch vụ"),
                            ("maintenance", "Thông báo bảo trì"),
                            ("general", "Thông báo chung"),
                        ],
                        max_length=30,
                        verbose_name="Loại thông báo",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Thấp"),
                            ("medium", "Trung bình"),
                            ("high", "Cao"),
                            ("emergency", "Khẩn cấp"),
                        ],
                        max_length=10,
                        verbose_name="Độ ưu tiên",
                    ),
                ),
                (
                    "send_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Thời gian gửi"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Đã đọc")),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="building.building",
                        verbose_name="Tòa nhà nhận thông báo",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="contract.contract",
                        verbose_name="Hợp đồng liên quan",
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="resident.resident",
                        verbose_name="Cư dân nhận thông báo",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="building.room",
                        verbose_name="Căn hộ nhận thông báo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thông báo",
                "verbose_name_plural": "Thông báo",
                "db_table": "notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["notification_type", "priority"],
                        name="notificatio_notific_58af76_idx",
                    )
                ],
            },
        ),
    ]
