# Generated by Django 5.2.7 on 2025-12-28 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("building", "0004_alter_room_options_building_total_availble_rooms_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationExpense",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expense_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã chi phí"
                    ),
                ),
                (
                    "expense_title",
                    models.CharField(max_length=255, verbose_name="Nội dung chi phí"),
                ),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("maintenance", "Chi phí bảo trì"),
                            ("utilities", "Chi phí tiện ích"),
                            ("salaries", "Chi phí lương nhân viên"),
                            ("security", "Chi phí an ninh"),
                            ("cleaning", "Chi phí vệ sinh"),
                            ("supplies", "Chi phí vật tư"),
                            ("other", "Chi phí khác"),
                        ],
                        max_length=20,
                        verbose_name="Loại chi phí",
                    ),
                ),
                ("date", models.DateField(verbose_name="Ngày chi phí")),
                ("count", models.IntegerField(default=1, verbose_name="Số lượng")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Số tiền/đơn vị (VNĐ)",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=15,
                        verbose_name="Tổng tiền (VNĐ)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("paid", "Đã thanh toán"),
                            ("unpaid", "Chưa thanh toán"),
                            ("overdue", "Quá hạn"),
                        ],
                        default="unpaid",
                        max_length=10,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Ghi chú"),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_expenses",
                        to="building.building",
                        verbose_name="Tòa nhà",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_expenses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người ghi nhận",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chi phí vận hành",
                "verbose_name_plural": "Chi phí vận hành",
            },
        ),
    ]
